#! /bin/bash
## Workspace Configurations
bspc monitor -d 1 2 3 4 5 6 7 8

## BSPC Configs
config() { bspc config "$@" & }
config border_width 4
config window_gap 10
config split_ratio 0.60

config borderless_monocle true
config gapless_monocle true
config single_monocle false
config focus_follows_pointer true

config pointer_modifier mod1 # mod4
config pointer_action1 move
config pointer_action2 resize_corner

## Window rules
bspc rule -r *:* # erase existing rules
rule() { bspc rule -a "$@" & }
rule firefox desktop=^1 follow=on focus=on
rule Code desktop=^2 follow=on focus=on
rule jetbrains-pycharm desktop=^2 follow=on focus=on
rule vlc desktop=^3 follow=on focus=on
# TODO: Check out archcraft-bspwm for more rules

## Launching Apps
killall -9 sxhkd dunst flameshot
sxhkd &
dunst &
flameshot &
"$HOME"/.config/bspwm/fehbg
"$HOME"/.config/polybar/launch.sh
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

## Misc
xsetroot -cursor_name left_ptr
